name = "Modpack"
author = "Quinn"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c0b5da13cbac34afb16dc4cab5c8b290b2165a6b48467561b393507cd0186776"

[versions]
fabric = "0.18.1"
minecraft = "1.21.10"
