name = "Modpack"
author = "Quinn"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "13d99e2b3acebe6a730dd76cc07b1a28fbee262efe404cb8cd2cebea83a95445"

[versions]
fabric = "0.18.1"
minecraft = "1.21.10"
